version: "3.9"

services:
  mia_bot:
    build: .
    restart: always
    env_file: config/config.env
    depends_on:
      - mongo
    volumes:
      - /tmp:/tmp

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: